
# generated by: jx gitops variables
export APP_NAME='integration-designer'
export BRANCH_NAME='main'
export BUILD_NUMBER='1'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='gcr.io'
export DOCKER_REGISTRY_ORG='prj-cicd-d-flowxai-jx-6401'
export DOMAIN='cicd.flowxai.dev'
export GIT_BRANCH='main'
export JENKINS_X_URL='https://dashboard-jx-old.cicd.flowxai.dev/flowx-ai/integration-designer/main/1'
export JX_CHART_REPOSITORY='http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo --cleanup'
export MINK_AS='tekton-bot'
export MINK_IMAGE='gcr.io/prj-cicd-d-flowxai-jx-6401/integration-designer:0.0.2'
export NAMESPACE_SUB_DOMAIN='-jx.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='gcr.io'
export REPO_NAME='integration-designer'
export REPO_OWNER='flowx-ai'
export VERSION='0.0.2'
export REPO_NAME=integration-designer
export GOOGLE_ARTIFACT_REGISTRY=europe-docker.pkg.dev/flowxai
export GOOGLE_ARTIFACT_REPOSITORY=backend-docker-release
export BASE_IMAGE_VARIANTS=''
export FLOWX_NEXT_VERSION=
